---
- name: Generate the SSH private key
  openssl_privatekey:
    path: "{{ SSH_keys.private }}"
    size: 2048
    state: present
    type: RSA

- name: Remove the existing public key (due to a bug in pyOpenSSL)
  file:
    path: "{{ SSH_keys.public }}"
    state: absent
  changed_when: false

- name: Generate the SSH public key
  openssl_publickey:
    path: "{{ SSH_keys.public }}"
    privatekey_path: "{{ SSH_keys.private }}"
    format: OpenSSH
  changed_when: false

- name: Change mode for the SSH private key
  file:
    path: "{{ SSH_keys.private }}"
    mode: 0600

- name: Ensure the dynamic inventory exists
  blockinfile:
    dest: configs/inventory.dynamic
    marker: "# {mark} ALGO MANAGED BLOCK"
    create: yes
    block: |
      [algo:children]
      {% for group in cloud_providers.keys() %}
      {{ group }}
      {% endfor %}
